### ISSUE TITLE
A roadmap for this package manager

### ISSUE THREAD

**Issue by MatusModder** [Matthew-s-Mutable-Linux-Distro/mmld-pkgman#1]
# What to do
Write your ideas below.
- [x] Implement basic functions like install, update and upgrade.
- [x] Make a config file for a package manager.
- [ ] Make a place where users can submit Mmldfiles. 
- [ ] Parallel downloads.
- [ ] Support for distros other than MMLD.
